// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFE.Persistence;

#nullable disable

namespace WFE.Persistence.Migrations
{
    [DbContext(typeof(WfeDbContext))]
    partial class WfeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WFE.Models.WfeActor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long?>("IntegrationAuthenticateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WfeActors", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeBusinessProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WfeBusinessProcesses", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeProcessInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CompletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForkTransitionName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("NextScheduledCheckTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ParentInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviousActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProcessSchemeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RootInstanceId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("State")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("ParentInstanceId");

                    b.HasIndex("RootInstanceId");

                    b.HasIndex("ProcessSchemeId", "Status");

                    b.HasIndex("Status", "NextScheduledCheckTime");

                    b.ToTable("WfeProcessInstance", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeProcessInstanceParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ForRootProcess")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ProcessInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessInstanceId", "Name")
                        .IsUnique();

                    b.ToTable("WfeProcessInstanceParameters", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeProcessScheme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedActivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefiningParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("bit");

                    b.Property<string>("RootSchemeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RootSchemeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SchemeId")
                        .HasColumnType("bigint");

                    b.Property<string>("StartingTransition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrackHistory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SchemeId");

                    b.HasIndex("RootSchemeId", "IsObsolete");

                    b.ToTable("WfeProcessSchemes", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeProcessTransitionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ExecutorActorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExecutorId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FromActivity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ProcessInstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTransitionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToActivity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TransitionName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutorActorId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("StartTransitionTime");

                    b.ToTable("WfeProcessTransitionsHistory", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeProcessWorkItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ClaimedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForkTransitionName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessSchemeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RootInstanceId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StartActivity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ParentInstanceId");

                    b.HasIndex("Status", "CreatedDateTime");

                    b.ToTable("WfeProcessWorkItems", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Enable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WfeRoles", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeScheme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessProcessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.ToTable("WfeSchemes", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeUserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ActorId", "RoleId")
                        .IsUnique();

                    b.ToTable("WfeUserRoles", (string)null);
                });

            modelBuilder.Entity("WFE.Models.WfeProcessInstance", b =>
                {
                    b.HasOne("WFE.Models.WfeProcessInstance", "ParentInstance")
                        .WithMany("ChildInstances")
                        .HasForeignKey("ParentInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WFE.Models.WfeProcessScheme", "ProcessScheme")
                        .WithMany()
                        .HasForeignKey("ProcessSchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentInstance");

                    b.Navigation("ProcessScheme");
                });

            modelBuilder.Entity("WFE.Models.WfeProcessInstanceParameter", b =>
                {
                    b.HasOne("WFE.Models.WfeProcessInstance", "ProcessInstance")
                        .WithMany("Parameters")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("WFE.Models.WfeProcessScheme", b =>
                {
                    b.HasOne("WFE.Models.WfeScheme", "SourceScheme")
                        .WithMany()
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceScheme");
                });

            modelBuilder.Entity("WFE.Models.WfeProcessTransitionHistory", b =>
                {
                    b.HasOne("WFE.Models.WfeActor", "ExecutorActor")
                        .WithMany("WfeProcessTransitionHistories")
                        .HasForeignKey("ExecutorActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WFE.Models.WfeProcessInstance", "ProcessInstance")
                        .WithMany("WfeProcessTransitionsHistory")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutorActor");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("WFE.Models.WfeProcessWorkItem", b =>
                {
                    b.HasOne("WFE.Models.WfeProcessInstance", "ParentInstance")
                        .WithMany()
                        .HasForeignKey("ParentInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentInstance");
                });

            modelBuilder.Entity("WFE.Models.WfeScheme", b =>
                {
                    b.HasOne("WFE.Models.WfeBusinessProcess", "BusinessProcess")
                        .WithMany("WfeSchemes")
                        .HasForeignKey("BusinessProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessProcess");
                });

            modelBuilder.Entity("WFE.Models.WfeUserRole", b =>
                {
                    b.HasOne("WFE.Models.WfeActor", "Actor")
                        .WithMany("WfeUserRoles")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WFE.Models.WfeRole", "Role")
                        .WithMany("WfeUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WFE.Models.WfeActor", b =>
                {
                    b.Navigation("WfeProcessTransitionHistories");

                    b.Navigation("WfeUserRoles");
                });

            modelBuilder.Entity("WFE.Models.WfeBusinessProcess", b =>
                {
                    b.Navigation("WfeSchemes");
                });

            modelBuilder.Entity("WFE.Models.WfeProcessInstance", b =>
                {
                    b.Navigation("ChildInstances");

                    b.Navigation("Parameters");

                    b.Navigation("WfeProcessTransitionsHistory");
                });

            modelBuilder.Entity("WFE.Models.WfeRole", b =>
                {
                    b.Navigation("WfeUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
